export const defaultState = [
  { make: 'Toyota', model: 'Celica', price: 35000, isDeleted: false, isDisabled: false },
  { make: 'Toyota', model: 'Celica', price: 35000, isDeleted: false, isDisabled: false },
  { make: 'Toyota', model: 'Celica', price: 35000, isDeleted: false, isDisabled: false },
  { make: 'Toyota', model: 'Celica', price: 35000, isDeleted: false, isDisabled: false },
  { make: 'Toyota', model: 'Celica', price: 35000, isDeleted: false, isDisabled: false },
  { make: 'Toyota', model: 'Celica', price: 35000, isDeleted: false, isDisabled: false },
  { make: 'Toyota', model: 'Celica', price: 35000, isDeleted: false, isDisabled: false },
  { make: 'Toyota', model: 'Celica', price: 35000, isDeleted: false, isDisabled: false },
  { make: 'Toyota', model: 'Celica', price: 35000, isDeleted: false, isDisabled: false },
  { make: 'Toyota', model: 'Celica', price: 35000, isDeleted: false, isDisabled: false },
  { make: 'Toyota', model: 'Celica', price: 35000, isDeleted: false, isDisabled: false },
  { make: 'Toyota', model: 'Celica', price: 35000, isDeleted: false, isDisabled: false },
  { make: 'Toyota', model: 'Celica', price: 35000, isDeleted: false, isDisabled: false },
  { make: 'Toyota', model: 'Celica', price: 35000, isDeleted: false, isDisabled: false },
  { make: 'Toyota', model: 'Celica', price: 35000, isDeleted: false, isDisabled: false },
  { make: 'Toyota', model: 'Celica', price: 35000, isDeleted: false, isDisabled: false },
  { make: 'Toyota', model: 'Celica', price: 35000, isDeleted: false, isDisabled: false },
  { make: 'Toyota', model: 'Celica', price: 35000, isDeleted: false, isDisabled: false },
];
